/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as OrchestrasIndexRouteImport } from './routes/orchestras/index'
import { Route as ModesIndexRouteImport } from './routes/modes/index'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments/index'
import { Route as DatabaseIndexRouteImport } from './routes/database/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs/$programId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrasIndexRoute = OrchestrasIndexRouteImport.update({
  id: '/orchestras/',
  path: '/orchestras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesIndexRoute = ModesIndexRouteImport.update({
  id: '/modes/',
  path: '/modes/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseIndexRoute = DatabaseIndexRouteImport.update({
  id: '/database/',
  path: '/database/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/database/': typeof DatabaseIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/modes/': typeof ModesIndexRoute
  '/orchestras/': typeof OrchestrasIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/artists': typeof ArtistsIndexRoute
  '/database': typeof DatabaseIndexRoute
  '/instruments': typeof InstrumentsIndexRoute
  '/modes': typeof ModesIndexRoute
  '/orchestras': typeof OrchestrasIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/database/': typeof DatabaseIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/modes/': typeof ModesIndexRoute
  '/orchestras/': typeof OrchestrasIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/programs/$programId'
    | '/artists/'
    | '/database/'
    | '/instruments/'
    | '/modes/'
    | '/orchestras/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/programs/$programId'
    | '/artists'
    | '/database'
    | '/instruments'
    | '/modes'
    | '/orchestras'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/programs/$programId'
    | '/artists/'
    | '/database/'
    | '/instruments/'
    | '/modes/'
    | '/orchestras/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  DatabaseIndexRoute: typeof DatabaseIndexRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
  ModesIndexRoute: typeof ModesIndexRoute
  OrchestrasIndexRoute: typeof OrchestrasIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestras/': {
      id: '/orchestras/'
      path: '/orchestras'
      fullPath: '/orchestras/'
      preLoaderRoute: typeof OrchestrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/': {
      id: '/modes/'
      path: '/modes'
      fullPath: '/modes/'
      preLoaderRoute: typeof ModesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database/': {
      id: '/database/'
      path: '/database'
      fullPath: '/database/'
      preLoaderRoute: typeof DatabaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  DatabaseIndexRoute: DatabaseIndexRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
  ModesIndexRoute: ModesIndexRoute,
  OrchestrasIndexRoute: OrchestrasIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
