name: iosApp
options:
  bundleIdPrefix: com.radiogolha
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [iosApp]
    info:
      path: iosApp/Info.plist
      properties:
        CFBundleIdentifier: com.radiogolha.ios
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.radiogolha.ios
      FRAMEWORK_SEARCH_PATHS: $(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    preBuildScripts:
      - name: Run Gradle Build
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
